### ISSUE TITLE
readOnly on @ApiModelProperty not considered in generation

### ISSUE THREAD

**Issue by anders-brolien** [kongchen/swagger-maven-plugin#379]
When adding a 
```
    @ApiModelProperty(value = "The name", required = true, example = "Parking", readOnly = false)
    private String name;
```
This is not considered for the generated output:
```
name:
        type: "string"
        example: "Parking"
        description: "The name of the POI"
        readOnly: true
```
The only way of getting readOnly: false or removing it completely seem to be to add a setName() metod to the java class. However I would prefer the generation to consider the swagger ApimodelProperty annotation on the elements in the java class.
