### ISSUE TITLE
Spring's @RequestParam not working correctly

### ISSUE THREAD

**Issue by pako-grape** [kongchen/swagger-maven-plugin#446]
There are empty names for parameters declared with @RequestParam annotation. For example:
```java
@RequestParam String username
```
and also even:
```java
@RequestParam(name = "username") String username
```
will be represented in swagger.yaml as:
```yaml
parameters:
- name: ""
  in: "query"
  required: true
  type: "string"
```
